/*
 * Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved.
 */
export const OPEN_PAGE_WORKFLOW_MENU = 'OPEN_PAGE_WORKFLOW_MENU';
export const CMS_EVENT_OPEN_PAGE_WORKFLOW_MENU = 'CMS_EVENT_OPEN_PAGE_WORKFLOW_MENU';
export const WORKFLOW_TASKS_MENU_OPENED_EVENT = 'WORKFLOW_TASKS_MENU_OPENED_EVENT';
export const WORKFLOW_DECISION_SELECTED_EVENT = 'WORKFLOW_DECISION_SELECTED_EVENT';
export const CMS_EVENT_OPEN_WORKFLOW_INBOX_DROPDOWN = 'CMS_EVENT_OPEN_WORKFLOW_INBOX_DROPDOWN';
export const WORKFLOW_ITEM_MENU_OPENED_EVENT = 'WORKFLOW_ITEM_MENU_OPENED_EVENT';
export const WORKFLOW_REFRESH_EVENT = 'WORKFLOW_REFRESH_EVENT';
